import:
  - ~/.config/alacritty/colour-schemes.yml
  - ~/.config/alacritty/keybindings.yml

env:
  TERM: xterm-256color

font:
  size: 9
  normal:
    family: noto sans mono

background_opacity: 0.85

