#! /bin/bash

MAX_WORKSPACES=6

#define icons for workspaces 1-9
# ic=(0     輸  " " " " )
# ic=(0 1 2 3 4 5 6 7 8 9)
ic=(0 一 二 三 四 五 六 七 八 九 〇)

hyprscripts="$HOME/.config/hypr/scripts"
workspaceScript="$hyprscripts/workspace"

getInfo() {
  MONITOR="$1"
  focusedWorkspace="$($workspaceScript -m $MONITOR current)"
  existingWorkspaces="$($workspaceScript -m $MONITOR list)"

  workspaces=()
  for i in `seq 1 $MAX_WORKSPACES`; do
    occupied=false
    if grep "\b$i\b" <<<"${existingWorkspaces[*]}" >/dev/null; then
      occupied=true
    fi
    focused=false
    if [ "$focusedWorkspace" -eq "$i" ]; then
      focused=true
    fi

    echo "{ \"index\": \"$i\", \"focused\": $focused, \"occupied\": $occupied, \"icon\": \"${ic[i]}\" }"
  done | jq -sc
}


module() {
  numMonitors=$(hyprctl monitors -j | jq ". | length")
  for i in `seq 0 $(expr $numMonitors - 1)`; do
    getInfo $i
  done | jq -sc

  #echo "" # add new line (important!)
}

module

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do
  # Check event type. Do nothing if event doesn't correspond with workspace changes.
  if grep -E "workspace|createworkspace|destroyworkspace|moveworkspace" <<<"$event" >/dev/null; then
    module
  fi
done
