#!/bin/bash

ids=($(bspc query -N -n $1.window))
options="$(xtitle "${ids[@]}" | awk '{ print ++i": "$0 }')"

[[ -n "$options" ]] || exit

id_index="$(rofi -dmenu -i -p 'System' -width 32 -line-padding 4 -padding 10 -lines 10 -font "Misc Termsyn 12" <<< "$options" | cut -d: -f1)"
[ "$id_index" ] || exit 

id="${ids[$((id_index - 1))]}"
bspc node $id --flag hidden=off
bspc node $id -f
