#!/bin/sh

IDLE_TIMEOUT=${1:-900}
IDLE_TIMEOUT_2=$(expr $IDLE_TIMEOUT + 5)

lockcmd='swaylock --screenshots --clock --effect-blur 20x3'

swayidle -w \
  timeout $IDLE_TIMEOUT "$HOME/.config/hypr/scripts/lock 5" \
  timeout $IDLE_TIMEOUT_2 "hyprctl dispatch dpms off" \
  before-sleep "$HOME/.config/hypr/scripts/lock" \
  resume "hyprctl dispatch dpms on"


